---
site_name: Enabling Hybrid Work with ThousandEyes
site_description: Enabling Hybrid Work with ThousandEyes
site_author: Omer Ilyas
copyright: Copyright &copy; 2023 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - search.suggest
    - content.code.copy
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - with-pdf:
      cover_title: Roadshow-WebexAmplify
      cover_subtitle: Enabling Hybrid Work with ThousandEyes
      cover_logo: assets/white_logo.png
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Lab:
      - Overview: overview.md
      - Task 1 - Lab Login and Setup: Task1.md
      - Task 2 - ThousandEyes Overview: Task2.md
      - Task 3 - Log into the Lab Environment: Task3.md
      - Task 4 - Install the ThousandEyes EPA: Task4.md
      - Task 5 - Configure ThousandEyes AST and EPA Monitoring: Task5.md
      - Task 6 - Analyzing ThousandEyes EPA Data: Task6.md
      - Task 7 - ThousandEyes Home Worker Dashboard (optional): Task7.md
      - Task 8 - Log out and Shutdown the Lab: Task8.md
      - Conclusion: conclusion.md
